// Mocks generated by Mockito 5.4.4 from annotations
// in notes_app_testing_starter/test/cubit/todo_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:hive/hive.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:notes_app_testing_starter/data/models/todo.dart' as _i4;
import 'package:notes_app_testing_starter/data/todo_local_data_source.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i3.LocalDataSource {
  @override
  _i2.Box<_i4.Todo> get todosBox => (super.noSuchMethod(
        Invocation.getter(#todosBox),
        returnValue: _FakeBox_0<_i4.Todo>(
          this,
          Invocation.getter(#todosBox),
        ),
        returnValueForMissingStub: _FakeBox_0<_i4.Todo>(
          this,
          Invocation.getter(#todosBox),
        ),
      ) as _i2.Box<_i4.Todo>);

  @override
  List<_i4.Todo> getTodos() => (super.noSuchMethod(
        Invocation.method(
          #getTodos,
          [],
        ),
        returnValue: <_i4.Todo>[],
        returnValueForMissingStub: <_i4.Todo>[],
      ) as List<_i4.Todo>);

  @override
  _i5.Future<void> addTodo(_i4.Todo? todo) => (super.noSuchMethod(
        Invocation.method(
          #addTodo,
          [todo],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTodo(_i4.Todo? todo) => (super.noSuchMethod(
        Invocation.method(
          #updateTodo,
          [todo],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTodo(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodo,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i4.Todo>> deleteTodoAndFetch(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodoAndFetch,
          [id],
        ),
        returnValue: _i5.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
      ) as _i5.Future<List<_i4.Todo>>);
}
